name: keyword
on:
  issues:
    types: [opened]

jobs:
  get-keyword:
    runs-on: ubuntu-latest
    outputs:
      keyword: ${{ steps.get-keyword.outputs.keyword }}
    steps:
    - name: checkout 
      uses: actions/checkout@v4
    - name: keyword-select
      id: get-keyword
      run: |
        echo keyword=Undefined >> $GITHUB_OUTPUT
        cat keyword-list.txt

        keywords=$(cat keyword-list.txt)
        for i in $keywords; do
          if [[ "${{ github.event.issue.title }}" =~ "$i" ]]; then
            echo keyword=$i >> $GITHUB_OUTPUT
          fi
        done
    - name: get output
      run: |
        echo ${{ steps.get-keyword.outputs.keyword }}
  slack:
    runs-on: ubuntu-latest
    needs: [get-keyword]
    if: needs.get-keyword.outputs.keyword != 'Undefined'
    strategy:
      matrix:
        environment: ["${{ needs.get-keyword.outputs.keyword }}"]
    environment: ${{ matrix.environment }}
    steps:
    - name: slack 
      uses: slackapi/slack-github-action@v1.24.0
      with:
        payload: |
          {
            "attachments": [
              {
                "pretext": "issue alert message",
                "color": "28a745",
                "fields": [
                  {
                    "title": "Level : ${{ needs.get-keyword.outputs.keyword }}",
                    "short": true,
                    "value": "issue url : ${{ github.event.issue.html_url }}"
                  }
                ]
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
