name: keyword
on:
  issues:
    types: [opened]

jobs:
  get-keyword:
    runs-on: ubuntu-latest
    outputs:
      keyword: ${{ steps.get-keyword.outputs.keyword }}
    steps:
    - name: checkout 
      uses: actions/checkout@v4
    - name: keyword-select
      id: get-keyword
      run: |
        echo keyword=Undefined >> $GITHUB_OUTPUT
        cat keyword-list.txt

        keywords=$(cat keyword-list.txt)
        for i in $keywords; do
          if [[ "${{ github.event.issue.title }}" =~ "$i" ]]; then
            echo keyword=$i >> $GITHUB_OUTPUT
          fi
        done
    - name: get output
      run: |
        echo ${{ steps.get-keyword.outpus.keyword }}

